apiVersion: v1
kind: Service
metadata:
  name: demo-testing
  namespace: testing-aks
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: demo-testing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80